resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: catalog-deployment
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: catalog-ingress
