services:

  mongo:
    image: mongo:8.0.11
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=omides248
      - MONGO_INITDB_ROOT_PASSWORD=123123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.75"
    networks:
      - db-network

  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      - POSTGRES_USER=omides248
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgresql.sh:/docker-entrypoint-initdb.d/init-db.sh
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
    networks:
      - db-network

  redis:
    image: redis:8.0.3
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    networks:
      - db-network

volumes:
  mongo-data:
  postgres-data:
  redis-data:

networks:
  db-network:
    driver: bridge